<?php

namespace chegamos\entity;

/**
 * Test class for Place.
 * Generated by PHPUnit on 2010-12-01 at 13:13:49.
 */
class PlaceTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Place
	 */
	protected $object;

	protected function setUp() {
		$this->place = new Place;
	}

	protected function tearDown() {
		unset($this->place);
	}

	public function testPopulate() {

		$subCategory = new Subcategory();
		$subCategory->setId(1234);
		$subCategory->setName("Self Service");

		$category = new Category();
		$category->setId(12);
		$category->setName("Restaurantes");
		$category->setSubCategory($subCategory);

		$city = new City();
		$city->setCountry("Brasil");
		$city->setState("SP");
		$city->setName("São Paulo");

		$address = new Address();
		$address->setCity($city);
		$address->setComplement("1 Andar");
   		$address->setDistrict("Vila Olimpia");
		$address->setNumber("129");
		$address->setStreet("Rua Funchal");
		$address->setZipcode("04551-069");

		$gasStation = new GasStation(
			array(
				'price_gas' => 1,23,
				'price_vodka' => 23,45
			)
		);

		$placeInfo = new PlaceInfo();
		$placeInfo->setGasStation($gasStation);

		$data = new \stdClass();
		$data->id = 123;
		$data->name = "Chegamos!";
		$data->average_rating = 4;
		$data->review_count = 3;
		$data->category = $category;
		$data->subcategory = $subCategory;
		$data->address = $address;
		$data->point->lat = "-23.529366";
		$data->point->lng = "-47.467117";
		$data->main_url = "http://chegamos.com/";
		$data->other_url = "http://chegamos.com.br/";
		$data->icon_url = "http://chegamos.com/img/icon.png";
		$data->description = "Description";
		$data->created = "01/12/2010 16:19";
		$data->phone = "11 2222-3333";
		$data->extended = $placeInfo;
		$data->num_visitors = 1024;
		$data->num_photos = 5;

		$this->place->populate($data);

		$this->assertEquals(123, $this->place->getId());
		$this->assertEquals("Chegamos!", $this->place->getName());
		$this->assertEquals(4, $this->place->getAverageRating());
		$this->assertEquals("Bom", $this->place->getAverageRatingString());
		$this->assertEquals(3, $this->place->getReviewCount());
		$this->assertEquals("chegamos\entity\Category", \get_class((object) $this->place->getCategory()));
		$this->assertEquals("Restaurantes - Self Service", (string) $this->place->getCategory());
		$this->assertEquals("chegamos\entity\Address", \get_class((object) $this->place->getAddress()));
		$this->assertEquals("Rua Funchal, 129 - Vila Olimpia<br/>São Paulo - SP", (string) $this->place->getAddress());
		$this->assertEquals("-23.529366,-47.467117", (string) $this->place->getPoint());
		$this->assertEquals("http://chegamos.com/", $this->place->getMainUrl());
		$this->assertEquals("http://chegamos.com.br/", $this->place->getOtherUrl());
		$this->assertEquals("http://chegamos.com/img/icon.png", $this->place->getIconUrl());
		$this->assertEquals("Description", $this->place->getDescription());
		$this->assertEquals("01/12/2010 16:19", $this->place->getCreated());
		$this->assertEquals("11 2222-3333", $this->place->getPhone());
		$this->assertEquals("chegamos\entity\PlaceInfo", \get_class((object) $this->place->getPlaceInfo()));
		$this->assertEquals(1024, $this->place->getNumVisitors());
		$this->assertEquals(5, $this->place->getNumPhotos());
	}

	public function testSetGetId() {
		$this->place->setId(123);
		$this->assertEquals(123, $this->place->getId());
	}

	public function testSetGetNumVisitors() {
		$this->place->setNumVisitors(1024);
		$this->assertEquals(1024, $this->place->getNumVisitors());
	}

	public function testSetGetNumPhotos() {
		$this->place->setNumPhotos(5);
		$this->assertEquals(5, $this->place->getNumPhotos());
	}

	public function testSetGetName() {
		$this->place->setName("Chegamos!");
		$this->assertEquals("Chegamos!", $this->place->getName());
	}

	public function testSetGetCreated() {
		$this->place->setCreated("01/12/2010 13:27");
		$this->assertEquals("01/12/2010 13:27", $this->place->getCreated());
	}

	public function testSetGetPlaceInfo() {
		$this->place->setPlaceInfo("Place Info?");
		$this->assertEquals("Place Info?", $this->place->getPlaceInfo());
	}

	public function testSetGetPhone() {
		$this->place->setPhone("Place Info?");
		$this->assertEquals("Place Info?", $this->place->getPhone());
	}

	public function testSetGetDescription() {
		$this->place->setDescription("Description");
		$this->assertEquals("Description", $this->place->getDescription());
	}

	public function testSetGetAverageRating() {
		$this->place->setAverageRating(1);
		$this->assertEquals(1, $this->place->getAverageRating());
		$this->place->setAverageRating(2);
		$this->assertEquals(2, $this->place->getAverageRating());
		$this->place->setAverageRating(3);
		$this->assertEquals(3, $this->place->getAverageRating());
		$this->place->setAverageRating(4);
		$this->assertEquals(4, $this->place->getAverageRating());
		$this->place->setAverageRating(5);
		$this->assertEquals(5, $this->place->getAverageRating());
	}

//	public function testSetGetAverageRatingString() {
//		$this->place->setAverageRatingString("String");
//		$this->assertEquals("String", $this->place->getAverageRatingString());
//	}

	public function testSetGetReviewCount() {
		$this->place->setReviewCount(3);
		$this->assertEquals(3, $this->place->getReviewCount());
	}

	public function testSetGetCategory() {
		$this->place->setCategory("String");
		$this->assertEquals("String", $this->place->getCategory());
	}

	public function testSetGetAddress() {
		$this->place->setAddress("Address");
		$this->assertEquals("Address", $this->place->getAddress());
	}

	public function testSetGetPoint() {
		$point = new Point();
		$point->setLat("-23.529366");
		$point->setLng("-47.467117");

		$this->place->setPoint($point);
		$this->assertEquals("-23.529366,-47.467117", (string) $this->place->getPoint());
	}

	public function testSetGetMainUrl() {
		$this->place->setMainUrl("http://chegamos.com/");
		$this->assertEquals("http://chegamos.com/", $this->place->getMainUrl());
	}

	public function testSetGetOtherUrl() {
		$this->place->setOtherUrl("http://chegamos.com/");
		$this->assertEquals("http://chegamos.com/", $this->place->getOtherUrl());
	}

	public function testSetGetIconUrl() {
		$this->place->setIconUrl("http://chegamos.com/img/logo.jpg");
		$this->assertEquals("http://chegamos.com/img/logo.jpg", $this->place->getIconUrl());
	}

	public function testGetRouteUrl() {
		//$this->assertEquals("http://chegamos.com/img/logo.jpg", $this->place->getIconUrl());
	}

}
